<?php

function cleanpp($string)
{

    $string = str_replace(' ', '-', $string); // Replaces all spaces with hyphens.
//$string = preg_replace('/[^A-Za-z0-9\-]/', '', $string); // Removes special chars.
    $string = strtolower($string);
    $utf8 = array(
        '/[áàâãªä]/u' => 'a',
        '/[ÁÀÂÃÄ]/u' => 'A',
        '/[ÍÌÎÏ]/u' => 'I',
        '/[íìîï]/u' => 'i',
        '/[éèêë]/u' => 'e',
        '/[ÉÈÊË]/u' => 'E',
        '/[óòôõºö]/u' => 'o',
        '/[ÓÒÔÕÖ]/u' => 'O',
        '/[úùûü]/u' => 'u',
        '/[ÚÙÛÜ]/u' => 'U',
        '/ç/' => 'c',
        '/Ç/' => 'C',
        '/ñ/' => 'n',
        '/Ñ/' => 'N',
        '/–/' => '-', // UTF-8 hyphen to "normal" hyphen
        '/[’‘‹›‚]/u' => ' ', // Literally a single quote
        '/[“”«»„]/u' => ' ', // Double quote
        '/ /' => ' ', // nonbreaking space (equiv. to 0x160)
    );

    return preg_replace(array_keys($utf8), array_values($utf8), $string); // Replaces multiple hyphens with single one.
}

$page = Mage::getStoreConfig('biztech_productpromotion/promotionsettings/frontendsettings', Mage::app()->getStore());
$showPromotion = Mage::getStoreConfig('biztech_productpromotion/promotionsettings/showpromotion', Mage::app()->getStore());
$limit = Mage::getStoreConfig('biztech_productpromotion/promotionsettings/setlimit', Mage::app()->getStore());
$limit = $limit ? round($limit) : 2;


$cartcount = $this->helper('checkout/cart')->getSummaryCount();
$quote = Mage::getModel('checkout/cart')->getQuote();

$promotionGift = $quote->getPromotionGift() ? $quote->getPromotionGift() : NULL;
$promotionAvailed = $quote->getPromotionAvailed() ? $quote->getPromotionAvailed() : 0;

if (($promotionAvailed != true) || ($promotionAvailed == true) && $showPromotion == 1) {
    if (Mage::helper('productpromotion')->isEnable() && $cartcount > 0 && $page == 'cartpage') {
        ?>


        <div class="please-wait" id="productpromotion-please-wait" style="display:none;">
            <div class="centered">
                <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw margin-bottom"></i>
            </div>
        </div>

        <?php
        $storeid = Mage::app()->getStore()->getStoreId();

        foreach ($quote->getAllItems() as $cartItem) {
            if ($cartItem->getProduct()->getId() == $promotionGift) {
                $item = $cartItem;

                if ($cartItem->getQty() > 1)
                    $cartTotal += (Mage::helper('tax')->getPrice($cartItem->getProduct(), $cartItem->getProduct()->getFinalPrice()) *
                        ($cartItem->getQty() - 1));
            } else {
                $cartTotal += (Mage::helper('tax')->getPrice($cartItem->getProduct(), $cartItem->getProduct()->getFinalPrice()) * $cartItem->getQty());
            }
        }

        $quoteSubTotal = $quote->getGrandTotal();

        $count = 0;
        $product_array = Array();


        //collection for promotion price lessthan carttotal
        $promotionCollection_lt = Mage::getModel('productpromotion/productpromotiondata')->getCollection()
            ->addFieldToFilter('promotion_price', array('lt' => $quoteSubTotal))
            ->addFieldToFilter('status', array('eq' => '1'))
            ->addFieldToFilter('store_id', array('eq' => $storeid))
            ->setOrder('promotion_price', 'ASC');
        $promotionCollection_lt->getSelect()->limit($limit);

        if (count($promotionCollection_lt) > 0) {
            foreach ($promotionCollection_lt->getData() as $key_lt => $promotion_lt) {
                $productIds['product_id'] = explode(",", $promotion_lt['product_id']);
                $count += count($productIds['product_id']);
                $productIds['promotion_price'] = $promotion_lt['promotion_price'];
                $productIds['promotion_id'] = $promotion_lt['productpromotion_id'];
                $product_array[] = $productIds;
            }
        }

        //collection for promotion price greaterthan carttotal
        $promotionCollection = Mage::getModel('productpromotion/productpromotiondata')->getCollection()
            ->addFieldToFilter('promotion_price', array('gteq' => $quoteSubTotal))
            ->addFieldToFilter('status', array('eq' => '1'))
            ->addFieldToFilter('store_id', array('eq' => $storeid))
            ->setOrder('promotion_price', 'ASC');
        $promotionCollection->getSelect()->limit($limit);


        if (count($promotionCollection) > 0) {
            foreach ($promotionCollection->getData() as $key => $promotion) {
                $productIds['product_id'] = explode(",", $promotion['product_id']);
                $count += count($productIds['product_id']);
                $productIds['promotion_price'] = $promotion['promotion_price'];
                $productIds['promotion_id'] = $promotion['productpromotion_id'];
                $product_array[] = $productIds;
            }
        }
        ?>

        <?php
        $availedProdcut = array();
        $i = 1;
        if ($count > 0):
            ?>
            <div id="promotions">
                <div id="promotion-title" class="page-title title-buttons">
                    <h1>
                        <?php
                        if (($promotionAvailed != true)):
                            $msg = Mage::getStoreConfig('biztech_productpromotion/promotionsettings/message', Mage::app()->getStore());
                            $helper = Mage::helper('cms');
                            if ($helper) {
                                $processor = $helper->getBlockTemplateProcessor();
                                if ($processor) {
                                    echo $content = $processor->filter($msg);
                                }
                            }
                        endif;
                        ?>
                    </h1>
                </div>
                <div id="promotion-products" class="promotion-products">
                    <ul class='products-grid'>
                        <?php
                        foreach ($product_array as $product_data) {
                            $cartPriceDifference = $this->getCartdifference($product_data['promotion_price']);
                            foreach ($product_data['product_id'] as $id_value) {
                                $_item = Mage::getModel('catalog/product')->load($id_value);
                                $productID = $_item->getId();
                                ?>
                                <?php
                                if (!(in_array($productID, $availedProdcut))):

                                    if ($_item->getIsInStock() == 1 && $_item->getStatus() == Mage_Catalog_Model_Product_Status::STATUS_ENABLED):
                                        ?>
                                        <li class="item">
                                            <div class="products-image float-center">
                                                <a title="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>"
                                                   class="product-image small-centered">
                                                    <img
                                                            src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(200); ?>"
                                                            width="200" height="200"
                                                            alt="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>"/>
                                                </a>
                                            </div>
                                            <?php if ($_item->getAttributeText('manufacturer')): ?>
                                                <?php $brand = $_item->getAttributeText('manufacturer') ?>
                                                <div class="product-brand">
                                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>catalog/brands/<?php echo cleanpp($brand) ?>.png"
                                                         alt="<?php echo $brand ?> Logo">
                                                </div>
                                            <?php endif; ?>
                                            <h3 class="product-name"><a title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><?php echo $_item->getName(); ?></a>
                                            </h3>

                                            <?php if (($cartPriceDifference > 0) && ($promotionAvailed != true)): ?>
                                                <div class="price-box">
                                                        <span class="regular-price">
                                                            <span class="price"> <?php echo 'noch ' ?> <?php echo Mage::helper('core')->currency($cartPriceDifference); ?></span>
                                                        </span>

                                                </div>
                                            <?php endif; ?>
                                            <div class="actions">
                                                <?php if (!($_item->getTypeInstance(true)->hasRequiredOptions($_item) || $_item->isGrouped())) { ?>
                                                    <button name="choose-gift" type="button"
                                                            class="button gift_btn<?php if (($cartPriceDifference > 0) || ($promotionAvailed == true)) { ?> disabled <?php } ?> "
                                                        <?php if (($cartPriceDifference > 0) || ($promotionAvailed == true)) { ?> disabled="disabled" <?php } ?>
                                                            title="<?php echo $this->__('Choose this gift') ?>"
                                                            id="<?php echo $id_value; ?>"
                                                            onclick="selectGift('<?php echo $id_value ?>', '<?php echo Mage::helper('checkout/cart')->getAddUrl($_item) ?>', '<?php echo $product_data['promotion_id'] ?>', '<?php echo $this->getUrl('productpromotion/index/setGift/') ?>')">
                                                            <span><span><?php echo $this->__('Choose this gift') ?></span>
                                                            </span>
                                                    </button>
                                                <?php } else { ?>
                                                    <button name="choose-gift" type="button"
                                                            class="button gift_btn<?php if (($cartPriceDifference > 0) || ($promotionAvailed == true)) { ?> disabled <?php } ?> "
                                                        <?php if (($cartPriceDifference > 0) || ($promotionAvailed == true)) { ?> disabled="disabled" <?php } ?>
                                                            title="<?php echo $this->__('Choose this gift') ?>"
                                                            id="<?php echo $id_value; ?>"
                                                            onclick="showOptions('<?php echo $_item->getId() . '_' . $product_data['promotion_id']; ?>')">
                                                            <span><span><?php echo $this->__('Choose this gift') ?></span>
                                                            </span>
                                                    </button>

                                                    <a href="<?php echo $this->getUrl('productpromotion/index/options', array('product_id' => $_item->getId(), 'promotionId' => $product_data['promotion_id'], 'page' => 'cart')); ?>"
                                                       class='fancybox'
                                                       id="fancybox_<?php echo $_item->getId() . '_' . $product_data['promotion_id']; ?>"
                                                       style='display:none'>
                                                    </a>
                                                <?php } ?>
                                            </div>
                                        </li>
                                    <?php
                                    endif;
                                endif;
                                $availedProdcut[] = $productID;
                                $i++;
                                ?>

                                <?php
                            }
                        }
                        ?>
                    </ul>
                </div>
            </div>
        <?php endif; ?>
        <?php
    }
}
?>

<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery('.fancybox').fancybox(
            {
                hideOnContentClick: true,
                width: 400,
                autoDimensions: true,
                type: 'iframe',
                showTitle: false,
                scrolling: 'no',
                onComplete: function () {
                    jQuery('#fancybox-frame').load(function () { // wait for frame to load and then gets it's height
                        jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height() + 70);
                        jQuery.fancybox.resize();
                    });

                }
            }
        );
    });
</script>
